language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - firebase use --add $FIREBASE_PROJECT
  - firebase target:apply hosting admin $FIREBASE_HOSTING_SITE

script:
  - ng build --prod
  - firebase deploy --token $FIREBASE_TOKEN

after_success:
  - echo Build Completed for Admin Web UI
